[package]

name = "rust-mpfr"
version = "0.0.1"
authors = [ "Bartłomiej Kamiński <fizyk20@gmail.com>" ]
repository = "https://github.com/fizyk20/rust-mpfr.git"

[lib]

name = "mpfr"
crate-type = ["dylib"]

[dependencies]
libc = "0.1.8"