[package]

name = "mpfr-rust"
version = "0.0.1"
authors = [ "Bartłomiej Kamiński <fizyk20@gmail.com>" ]
repository = "https://github.com/fizyk20/rust-mpfr.git"

[lib]

name = "mpfr_rust"
crate-type = ["dylib"]

[dependencies]
libc = "0.1.8"

[dependencies.rust-gmp]
git = "https://github.com/fizyk20/rust-gmp.git"
branch = "rust1.0"